version: '3.8'
services:
  postgres-library:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres-library-data:/var/lib/postgresql/data
volumes:
  postgres-library-data:
    driver: local


# If needed:
# https://stackoverflow.com/questions/38249434/docker-postgres-failed-to-bind-tcp-0-0-0-05432-address-already-in-use